### ISSUE TITLE
run failed

### ISSUE THREAD

**Issue by eryajf** [matchai/waka-box#132]
I got this msg:

```
(node:1608) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (/home/runner/work/_actions/matchai/waka-box/master/dist/index.js:372:15)
    at settle (/home/runner/work/_actions/matchai/waka-box/master/dist/index.js:6127:11)
    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/matchai/waka-box/master/dist/index.js:7027:15)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:1608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1608) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

see: https://github.com/eryajf/Weekly-development-breakdown/runs/7588551751?check_suite_focus=true

**Comment by eryajf** [comment]
It should be because I just applied for no data yet. When I configured the plug-in, I will not report any errors. The step of configuring the plug-in is also added to the documentation.
