### ISSUE TITLE
Run failure:  TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by elliottower** [matchai/waka-box#135]
On the `Update gist` part of the action, I get this error:

```
Run matchai/waka-box@master
/home/runner/work/_actions/matchai/waka-box/master/dist/index.js:861
      for (let t = 0; t < Math.min(e.data.languages.length, 5); t++) {
                                                    ^

TypeError: Cannot read properties of undefined (reading 'length')
    at updateGist (/home/runner/work/_actions/matchai/waka-box/master/dist/index.js:861:53)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/home/runner/work/_actions/matchai/waka-box/master/dist/index.js:848:7)
    at async /home/runner/work/_actions/matchai/waka-box/master/dist/index.js:901:7
```

I checked on my dashboard and though I just created the account I do have logs for two languages so it shouldn't be getting an error. I checked that my token and API key were correct as well.

**Comment by elliottower** [comment]
Okay it looks like my public profile shows no activity despite my dashboard showing ~12 mins of coding, the FAQ says the public profiles use a 15 minute timeout so I'm guess it it will work at some point in the future once it refreshes. 

Might be worth updating the documentation to indicate some of these things though, like when signing up for an account you have to specifically enable sharing coding time and such publicly, which some people may miss (I searched for it in the settings after setting my profile up and couldn't find it, not sure where the setting is even located although I remember setting it)

**Comment by huccct** [comment]
bro, i got the same question, so how to handle it?

**Comment by elliottower** [comment]
See my above comment and the documentation (don't remember much about it this many months after)

**Comment by huccct** [comment]
okay, thank u, i got it.
