### ISSUE TITLE
Error While Running in Github Actions

### ISSUE THREAD

**Issue by varunsridharan** [matchai/waka-box#3]
Hi There

i am trying to use this. but the build keeps failing

below is the error

```
husky > setting up git hooks
Can't find .git, skipping Git hooks installation.
Please check that you're in a cloned repository or run 'git init' to create an empty Git repository and reinstall husky.
added 118 packages in 2.78s
 ---> c139b9f3c366
Step 8/9 : COPY . .
 ---> b22be3af2e2f
Step 9/9 : ENTRYPOINT ["node", "index.js"]
 ---> Running in 3730a2e3a038
 ---> ccfc3f82d7a6
Successfully built ccfc3f82d7a6
Successfully tagged gcr.io/gct-12-k5ytrsuh3ccqn8dwf3qf8k5/2e80e41d2b8a4d20e10a5adc527c061627b84ee7a6fbb1e6133f9f47f87f48fa/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1:fc613b4dfd6736a7bd268c8a0e74ed0d1c04a959f59dd74ef2874983fd443fc9
Already have image (with digest): gcr.io/github-actions-images/action-runner:latest
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/github/workspace/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

### FAILED update-gist 01:23:09Z (26.226s)

```

**Comment by matchai** [comment]
Unfortunately, I haven't been able to reproduce this issue.
This may have been an intermittent issue with the base image or GitHub Actions itself. I would suggest trying again or following up with more details around the failure.

**Comment by varunsridharan** [comment]
@matchai i tried again but same

**NOTE** if i fork this repo the action is not getting triggered so i had to create a new repo which includes your github action into it.

https://github.com/varunsridharan/gist-box

## Workflow Code
```
workflow "Update gist with WakaTime stats" {
  resolves = ["update-gist"]
  on = "schedule(*/10 * * * *)"
}

workflow "Update gist On Push WakaTime stats" {
  resolves = ["update-gist"]
  on = "Push"
}

action "update-gist" {
  uses = "matchai/waka-box@master"
  secrets = [
    "GH_TOKEN",
    "WAKATIME_API_KEY",
    "GITHUB_TOKEN",
  ]
  env = {
    GIST_ID = "06875b54eda43ce1b215770e08f22c5d"
  }
}
```

## Response 
```
### STARTED update-gist 05:31:55Z

Pulling image: gcr.io/github-actions-images/action-runner:latest
latest: Pulling from github-actions-images/action-runner
169185f82c45: Pulling fs layer
0ccde4b6b241: Pulling fs layer
d0372f57daa2: Pulling fs layer
165911d108d6: Pulling fs layer
54996bce1de5: Pulling fs layer
165911d108d6: Waiting
54996bce1de5: Waiting
0ccde4b6b241: Verifying Checksum
0ccde4b6b241: Download complete
169185f82c45: Verifying Checksum
169185f82c45: Download complete
d0372f57daa2: Download complete
165911d108d6: Verifying Checksum
165911d108d6: Download complete
54996bce1de5: Verifying Checksum
54996bce1de5: Download complete
169185f82c45: Pull complete
0ccde4b6b241: Pull complete
d0372f57daa2: Pull complete
165911d108d6: Pull complete
54996bce1de5: Pull complete
Digest: sha256:c9bb432ec5ec08ee08b040a9fccacebbbf8a91444dac4721600cf5dca9dae57e
Status: Downloaded newer image for gcr.io/github-actions-images/action-runner:latest
fc613b4dfd6736a7bd268c8a0e74ed0d1c04a959f59dd74ef2874983fd443fc9: Pulling from gct-12-k5ytrsuh3ccqn8dwf3qf8k5/29bf9af0c557fdc53454e1977af073487fbd11adb856520a86bcf600cd321842/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1
e7c96db7181b: Already exists
bbec46749066: Pulling fs layer
89e5cf82282d: Pulling fs layer
5de6895db72f: Pulling fs layer
abf99aeb669c: Pulling fs layer
1e61b1d49f77: Pulling fs layer
deb4671f3052: Pulling fs layer
abf99aeb669c: Waiting
1e61b1d49f77: Waiting
deb4671f3052: Waiting
5de6895db72f: Verifying Checksum
5de6895db72f: Download complete
89e5cf82282d: Verifying Checksum
89e5cf82282d: Download complete
abf99aeb669c: Verifying Checksum
abf99aeb669c: Download complete
bbec46749066: Verifying Checksum
bbec46749066: Download complete
1e61b1d49f77: Verifying Checksum
1e61b1d49f77: Download complete
deb4671f3052: Verifying Checksum
deb4671f3052: Download complete
bbec46749066: Pull complete
89e5cf82282d: Pull complete
5de6895db72f: Pull complete
abf99aeb669c: Pull complete
1e61b1d49f77: Pull complete
deb4671f3052: Pull complete
Digest: sha256:3d59c4f0bcd088f9733db9893f25b59991b9f7bf77a0e3e288eca77f69d6d05d
Status: Downloaded newer image for gcr.io/gct-12-k5ytrsuh3ccqn8dwf3qf8k5/29bf9af0c557fdc53454e1977af073487fbd11adb856520a86bcf600cd321842/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1:fc613b4dfd6736a7bd268c8a0e74ed0d1c04a959f59dd74ef2874983fd443fc9
Step 1/9 : FROM node:lts-alpine
lts-alpine: Pulling from library/node
e7c96db7181b: Already exists
bbec46749066: Already exists
89e5cf82282d: Already exists
5de6895db72f: Already exists
Digest: sha256:07897ec27318d8e43cfc6b1762e7a28ed01479ba4927aca0cdff53c1de9ea6fd
Status: Downloaded newer image for node:lts-alpine
 ---> 9dfa73010b19
Step 2/9 : LABEL "com.github.actions.name"="waka-box"
 ---> Using cache
 ---> 3fb520c8e5bb
Step 3/9 : LABEL "com.github.actions.description"="Update a pinned gist to contain WakaTime stats"
 ---> Using cache
 ---> 182ccd7bde4d
Step 4/9 : LABEL "com.github.actions.icon"="clipboard"
 ---> Using cache
 ---> 426f7978f410
Step 5/9 : LABEL "com.github.actions.color"="blue"
 ---> Using cache
 ---> 8576901767bb
Step 6/9 : COPY package*.json ./
 ---> Using cache
 ---> 1fe4f48706dc
Step 7/9 : RUN npm ci
 ---> Using cache
 ---> 1a5b1a5c4453
Step 8/9 : COPY . .
 ---> Using cache
 ---> d8d60a28d390
Step 9/9 : ENTRYPOINT ["node", "index.js"]
 ---> Using cache
 ---> 302b0bf1b797
Successfully built 302b0bf1b797
Successfully tagged gcr.io/gct-12-k5ytrsuh3ccqn8dwf3qf8k5/29bf9af0c557fdc53454e1977af073487fbd11adb856520a86bcf600cd321842/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1:fc613b4dfd6736a7bd268c8a0e74ed0d1c04a959f59dd74ef2874983fd443fc9
Already have image (with digest): gcr.io/github-actions-images/action-runner:latest
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/github/workspace/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

### FAILED update-gist 05:32:16Z (20.837s)
```

**Comment by g1eny0ung** [comment]
@varunsridharan I ask this question in GitHub Community. The forked repo can be triggered according to this solution: https://github.community/t5/GitHub-Actions/Forked-repo-doesn-t-trigger-action/m-p/32575#M1189.
