### ISSUE TITLE
Buffer Error

### ISSUE THREAD

**Issue by alinbasuljevic** [matchai/waka-box#38]
buffer.js:327
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:327:9)
    at new e (C:\Users\resel\Downloads\waka-box-master\waka-box-master\dist\index.js:6476:26)
    at Object.104 (C:\Users\resel\Downloads\waka-box-master\waka-box-master\dist\index.js:844:15)
    at __webpack_require__ (C:\Users\resel\Downloads\waka-box-master\waka-box-master\dist\index.js:9:10)
    at startup (C:\Users\resel\Downloads\waka-box-master\waka-box-master\dist\index.js:15:12)
    at C:\Users\resel\Downloads\waka-box-master\waka-box-master\dist\index.js:17:10
    at Object.<anonymous> (C:\Users\resel\Downloads\waka-box-master\waka-box-master\dist\index.js:18:3)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by SailerNote** [comment]
Parameter parsing error Failure to correctly read required parameters from environment variables will cause this error. Check whether the project settings/secrets parameter name and the two token values are correct. Maybe it will help.
